# Ce dossier est utilisé pour afficher ce projet sur mon site web (https://smartineau.me)
# This folder is used to display this project on my website (https://smartineau.me)
titre = "MémoMath"
etiquettes = ["unity", "csharp"]
dossier = "expo-sciences"
contenu = "/README.md"
date_de_creation = 2020-06-18T20:43:58.947Z
